// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASTkLzO5jfM36tSxBwI-VNoGqLWMC6WWE',
    appId: '1:1078990127055:web:b718fd76b07ed231e19cba',
    messagingSenderId: '1078990127055',
    projectId: 'hackathon-cc87f',
    authDomain: 'hackathon-cc87f.firebaseapp.com',
    storageBucket: 'hackathon-cc87f.appspot.com',
    measurementId: 'G-0DE77ZBK7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA4usdnt9j9tNAB86u7cxHu1VWDq0iRsI',
    appId: '1:1078990127055:android:86db3a139c5340a6e19cba',
    messagingSenderId: '1078990127055',
    projectId: 'hackathon-cc87f',
    storageBucket: 'hackathon-cc87f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6x4f2WYiEdnmOy4fDzVisq30AXEhnc9Y',
    appId: '1:1078990127055:ios:ee4e3d17978e46f8e19cba',
    messagingSenderId: '1078990127055',
    projectId: 'hackathon-cc87f',
    storageBucket: 'hackathon-cc87f.appspot.com',
    iosClientId: '1078990127055-k9pcbq9bmmvlpu23tj2elarp142pbkfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6x4f2WYiEdnmOy4fDzVisq30AXEhnc9Y',
    appId: '1:1078990127055:ios:ee4e3d17978e46f8e19cba',
    messagingSenderId: '1078990127055',
    projectId: 'hackathon-cc87f',
    storageBucket: 'hackathon-cc87f.appspot.com',
    iosClientId: '1078990127055-k9pcbq9bmmvlpu23tj2elarp142pbkfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon',
  );
}
